# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'The Agency'
description: 'The AI/ML club at GT.'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://gtagency.github.io' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Defaults
defaults:
    - scope:
        path: ''
        type: 'posts'
      values:
        layout: post
        includecss: aesthic.css
        moreexists: true
        permalink: /:year/:title
        author: GT Agency
    - scope:
        path: 'photos/'
      values:
        photo: true

# PAGINATION
paginate: 5

# Posted in ... with ...
sechby: 
  category:   #in
  tag:   #with

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-paginate
